//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySwoleMateTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Trainer_FK { get; set; }
        public int Trainee_FK { get; set; }
        public int From_FK { get; set; }
        public string Message1 { get; set; }
    
        public virtual Trainee Trainee { get; set; }
        public virtual Trainee Trainee1 { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Trainer Trainer1 { get; set; }
    }
}
