//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySwoleMateTemp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySwoleMateEntities : DbContext
    {
        public MySwoleMateEntities()
            : base("name=MySwoleMateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avaliablity> Avaliablities { get; set; }
        public virtual DbSet<Exercis> Exercises { get; set; }
        public virtual DbSet<Gym> Gyms { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<MealPlan> MealPlans { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PayScale> PayScales { get; set; }
        public virtual DbSet<Trainee> Trainees { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Workout> Workouts { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
    }
}
